version: '3.8'
services:
 frontend:
  build:
   dockerfile: "NextGen-BM-FE/Dockerfile"
  ports:
   - "5173:5173"
  depends_on:
   - backend
  env_file: "vite.env"
  healthcheck:
   test: "curl -o /dev/null --fail http://0.0.0.0:5173/ || exit 1"
   interval: 30s
   timeout: 30s
   retries: 2
   start_period: 60s
 backend:
  build: 
   dockerfile: "NextGen-BM-BE/Dockerfile"
  ports:
   - "5204:5204"
   - "7261:7261"
  volumes:
   - ~/.microsoft/usersecrets/346e6da5-0d5a-4edd-8a31-b014199b62dc:/root/.microsoft/usersecrets/346e6da5-0d5a-4edd-8a31-b014199b62dc
  env_file: "aspnet.env"
  healthcheck:
   test: "curl -k --fail https://0.0.0.0:7261/Health/check || exit 1"
   interval: 30s
   timeout: 30s
   retries: 2
   start_period: 60s





   