export const requiredErrors = {
  alias: "Alias is required!",
  floorNum: "Number of floors is required!",
  totalBuildingSize: "Total Building Size is required!",
  dateBuilt: "Date built is required!",
  numOfElevators: "Number of Elevators is required!",
  streetName: "Street Name is required!",
  streetNumber: "Street Number is required!",
  district: "District is required!",
  city: "City is required!",
  country: "Country is required!",
  postalCode: "Postal code is required!",
  responsibleRole: "Responsible role is required!",
  description: "Description is required!",
  startDate: "Start Date is required!",
  endDate: "End Date is required!",
  price: "Price is required!",
  amountOwed: "Amount is required!",
  dateOpened: "Date Opened is required!",
  dueDate: "Due Date is required!",
  status: "Status is required!",
  paymentMethod: "Payment method is required!",
};

export const valueErrors = {
  aliasMinCharacter: "Alias must be at least 3 characters long!",
  buildingSizeNegative: "Building size cannot be negative or 0!",
  floorNumNegative: "Number of floors cannot be negative or 0!",
  numOfElevatorsNegative: "Number of elevators cannot be negative!",
  streetNumberNegative: "Street number cannot be negative or 0!",
  endDateCurrentMonth: "End date cannot be in the current month!",
  endDateBeforeStartDate: "End date cannot be before start date!",
  priceNegative: "Price cannot be negative!",
  propertySizeNegative: "Property size can't be negative!",
  propertySizeOfIdealParts: "The size of ideal parts is in % (between 0 and 100)!",
  propertyNumberTaken: "Number already in use!",
  propertyInvalidFloor: "Invalid floor number"
  amountOwedNegative: "Amount cannot be negative!",
  dueDateBeforeDateOpened: "Due date cannot be before date opened!",
  noExpenses: "There are no expenses, so you cannot make a payment!",
};
