// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextGen_BM_BE_Infrastructure;

#nullable disable

namespace NextGen_BM_BE_Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator().HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.BuildingAggregate.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DeletedDate")
                        .HasColumnType("date");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entrance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.BuildingAggregate.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuildingId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateBuilt")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DeletedDate")
                        .HasColumnType("date");

                    b.Property<int>("FloorNum")
                        .HasColumnType("int");

                    b.Property<int>("NumOfElevators")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBuildingSize")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BuildingId");

                    b.HasIndex("AddressId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.BuildingAggregate.BuildingExpense", b =>
                {
                    b.Property<int>("BuildingExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuildingExpenseId"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOpened")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DeletedDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<int?>("RepeatPeriodIdEnumsId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierIdEnumsId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BuildingExpenseId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("RepeatPeriodIdEnumsId");

                    b.HasIndex("SupplierIdEnumsId");

                    b.ToTable("BuildingExpenses");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.Enums", b =>
                {
                    b.Property<int>("EnumsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnumsId"));

                    b.Property<DateOnly?>("DeletedDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("EnumsId");

                    b.ToTable("Enums");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.PropertyAggregate.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DeletedDate")
                        .HasColumnType("date");

                    b.Property<bool>("EntranceIsExternal")
                        .HasColumnType("bit");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<int>("PropertyNumber")
                        .HasColumnType("int");

                    b.Property<int>("PropertyTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SizeOfIdealParts")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PropertyId");

                    b.HasIndex("BuildingId");

                    b.ToTable("Property");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.PropertyAggregate.PropertyExpense", b =>
                {
                    b.Property<int>("PropertyExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyExpenseId"));

                    b.Property<DateOnly?>("DeletedDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PropertyExpenseTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("RoleId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("PropertyExpenseId");

                    b.HasIndex("PropertyExpenseTemplateId");

                    b.HasIndex("RoleId1");

                    b.ToTable("PropertyExpense");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.PropertyAggregate.PropertyPayments", b =>
                {
                    b.Property<int>("PropertyPaymentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyPaymentsId"));

                    b.Property<decimal>("AmountOwed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("DateOpened")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DeletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentParentId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyExpenseId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("PropertyPaymentsId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("PropertyExpenseId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("StatusId");

                    b.ToTable("PropertyPayments");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.PropertyAggregate.PropertyResidents", b =>
                {
                    b.Property<int>("PropertyResidentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyResidentsId"));

                    b.Property<DateOnly?>("DeletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EnterDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("LeaveDate")
                        .HasColumnType("date");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("ResidentTypeId")
                        .HasColumnType("int");

                    b.HasKey("PropertyResidentsId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyResident");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.PropertyAggregate.PropertyUsers", b =>
                {
                    b.Property<int>("PropertyUsersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyUsersId"));

                    b.Property<DateOnly?>("DeletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<decimal>("PercentOfApartmentOwned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("RoleId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PropertyUsersId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("RoleId1");

                    b.HasIndex("UserId1");

                    b.ToTable("PropertyUsers");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.PropertyExpenseTemplate", b =>
                {
                    b.Property<int>("PropertyExpenseTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyExpenseTemplateId"));

                    b.Property<DateOnly?>("DeletedDate")
                        .HasColumnType("date");

                    b.Property<string>("ExpenseTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PerResident")
                        .HasColumnType("bit");

                    b.Property<int>("RepeatPeriodId")
                        .HasColumnType("int");

                    b.HasKey("PropertyExpenseTemplateId");

                    b.HasIndex("RepeatPeriodId");

                    b.ToTable("PropertyExpenseTemplate");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.RequestAggregate.RepairRequest", b =>
                {
                    b.Property<int>("RepairRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepairRequestId"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOpened")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateSettled")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DeletedDate")
                        .HasColumnType("date");

                    b.Property<string>("RequestDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestStatusId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RepairRequestId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("RequestStatusId");

                    b.HasIndex("UserId1");

                    b.ToTable("RepairRequests");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.RequestAggregate.RequestNotes", b =>
                {
                    b.Property<int>("RequestNotesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestNotesId"));

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DeletedDate")
                        .HasColumnType("date");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RepairRequestId")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RequestNotesId");

                    b.HasIndex("RepairRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("RequestNotes");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.UserBuildings", b =>
                {
                    b.Property<int>("UserBuildingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserBuildingsId"));

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DeletedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("RoleId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserBuildingsId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("RoleId1");

                    b.HasIndex("UserId1");

                    b.ToTable("UserBuildings");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.Role", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.HasDiscriminator().HasValue("Role");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NextGen_BM_BE_Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NextGen_BM_BE_Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextGen_BM_BE_Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NextGen_BM_BE_Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.BuildingAggregate.Building", b =>
                {
                    b.HasOne("NextGen_BM_BE_Domain.Entities.BuildingAggregate.Address", "BuildingAddress")
                        .WithMany("Buildings")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildingAddress");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.BuildingAggregate.BuildingExpense", b =>
                {
                    b.HasOne("NextGen_BM_BE_Domain.Entities.BuildingAggregate.Building", "Building")
                        .WithMany("BuildingExpenses")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextGen_BM_BE_Domain.Entities.Enums", "RepeatPeriodId")
                        .WithMany("RepeatPeriod")
                        .HasForeignKey("RepeatPeriodIdEnumsId");

                    b.HasOne("NextGen_BM_BE_Domain.Entities.Enums", "SupplierId")
                        .WithMany("Supplier")
                        .HasForeignKey("SupplierIdEnumsId");

                    b.Navigation("Building");

                    b.Navigation("RepeatPeriodId");

                    b.Navigation("SupplierId");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.PropertyAggregate.Property", b =>
                {
                    b.HasOne("NextGen_BM_BE_Domain.Entities.BuildingAggregate.Building", "Building")
                        .WithMany("Properties")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.PropertyAggregate.PropertyExpense", b =>
                {
                    b.HasOne("NextGen_BM_BE_Domain.Entities.PropertyExpenseTemplate", "PropertyExpenseTemplate")
                        .WithMany()
                        .HasForeignKey("PropertyExpenseTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextGen_BM_BE_Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId1");

                    b.Navigation("PropertyExpenseTemplate");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.PropertyAggregate.PropertyPayments", b =>
                {
                    b.HasOne("NextGen_BM_BE_Domain.Entities.Enums", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId");

                    b.HasOne("NextGen_BM_BE_Domain.Entities.PropertyAggregate.PropertyExpense", "PropertyExpense")
                        .WithMany()
                        .HasForeignKey("PropertyExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextGen_BM_BE_Domain.Entities.PropertyAggregate.Property", "Property")
                        .WithMany("Payments")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextGen_BM_BE_Domain.Entities.Enums", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Property");

                    b.Navigation("PropertyExpense");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.PropertyAggregate.PropertyResidents", b =>
                {
                    b.HasOne("NextGen_BM_BE_Domain.Entities.PropertyAggregate.Property", "Property")
                        .WithMany("PropertyResidents")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.PropertyAggregate.PropertyUsers", b =>
                {
                    b.HasOne("NextGen_BM_BE_Domain.Entities.PropertyAggregate.Property", "Property")
                        .WithMany("Users")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextGen_BM_BE_Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId1");

                    b.HasOne("NextGen_BM_BE_Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("Property");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.PropertyExpenseTemplate", b =>
                {
                    b.HasOne("NextGen_BM_BE_Domain.Entities.Enums", "RepeatPeriod")
                        .WithMany()
                        .HasForeignKey("RepeatPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepeatPeriod");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.RequestAggregate.RepairRequest", b =>
                {
                    b.HasOne("NextGen_BM_BE_Domain.Entities.BuildingAggregate.Building", "Building")
                        .WithMany("RepairRequests")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextGen_BM_BE_Domain.Entities.Enums", "RequestStatus")
                        .WithMany("RepairRequests")
                        .HasForeignKey("RequestStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextGen_BM_BE_Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("Building");

                    b.Navigation("RequestStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.RequestAggregate.RequestNotes", b =>
                {
                    b.HasOne("NextGen_BM_BE_Domain.Entities.RequestAggregate.RepairRequest", null)
                        .WithMany("Notes")
                        .HasForeignKey("RepairRequestId");

                    b.HasOne("NextGen_BM_BE_Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.UserBuildings", b =>
                {
                    b.HasOne("NextGen_BM_BE_Domain.Entities.BuildingAggregate.Building", "Building")
                        .WithMany("UserBuildings")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextGen_BM_BE_Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId1");

                    b.HasOne("NextGen_BM_BE_Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("Building");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.BuildingAggregate.Address", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.BuildingAggregate.Building", b =>
                {
                    b.Navigation("BuildingExpenses");

                    b.Navigation("Properties");

                    b.Navigation("RepairRequests");

                    b.Navigation("UserBuildings");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.Enums", b =>
                {
                    b.Navigation("RepairRequests");

                    b.Navigation("RepeatPeriod");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.PropertyAggregate.Property", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("PropertyResidents");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NextGen_BM_BE_Domain.Entities.RequestAggregate.RepairRequest", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
